#!/usr/bin/env sh
set -eu

repo_dir="$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)"
checkout="${CHIPYARD_CHECKOUT:-$repo_dir/external/chipyard}"
sim_dir="$checkout/sims/verilator"
config="${CHIPYARD_CONFIG:-OpenPhoneRocketConfig}"
config_package="${CHIPYARD_CONFIG_PACKAGE:-openphone}"

cd "$repo_dir"
CHIPYARD_CHECKOUT="$checkout" python3 scripts/check_chipyard_verilator_preflight.py

cd "$sim_dir"
# env.sh is generated by Chipyard setup and provides RISCV plus toolchain paths.
# shellcheck disable=SC1091
. ../../env.sh
if [ -z "${RISCV:-}" ] && [ -d "$repo_dir/external/riscv-tools-linux-x64" ]; then
	RISCV="$repo_dir/external/riscv-tools-linux-x64"
	export RISCV
fi
if [ -d "$repo_dir/external/riscv-tools-linux-x64/bin" ]; then
	PATH="$repo_dir/external/riscv-tools-linux-x64/bin:$PATH"
	export PATH
fi

exec make CONFIG="$config" CONFIG_PACKAGE="$config_package" "$@"
