#!/usr/bin/env sh
set -eu

repo_dir="$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)"
checkout="${CHIPYARD_CHECKOUT:-$repo_dir/external/chipyard}"
sim_dir="$checkout/sims/verilator"
config="${CHIPYARD_CONFIG:-OpenPhoneRocketConfig}"
config_package="${CHIPYARD_CONFIG_PACKAGE:-openphone}"

cd "$repo_dir"
CHIPYARD_CHECKOUT="$checkout" python3 scripts/check_chipyard_verilator_preflight.py

cd "$sim_dir"
# env.sh is generated by Chipyard setup and provides RISCV plus toolchain paths.
# shellcheck disable=SC1091
. ../../env.sh

exec make CONFIG="$config" CONFIG_PACKAGE="$config_package" "$@"
