# Import this directory into an external Linux tree and source Kconfig from
# drivers/misc/Kconfig or another board-owned driver menu.
obj-$(CONFIG_OPENAGENT_E1_NPU)         += e1-npu.o
obj-$(CONFIG_OPENAGENT_E1_DMA)         += e1-dma.o
obj-$(CONFIG_OPENAGENT_E1_CLINT_TIMER) += e1-clint-timer.o
obj-$(CONFIG_OPENAGENT_E1_PLIC)        += e1-plic.o
