# Import this directory into an external Linux tree and source Kconfig from
# drivers/misc/Kconfig or another board-owned driver menu.
obj-$(CONFIG_OPENPHONE_HELLO_NPU)         += hello-npu.o
obj-$(CONFIG_OPENPHONE_HELLO_DMA)         += hello-dma.o
obj-$(CONFIG_OPENPHONE_HELLO_CLINT_TIMER) += hello-clint-timer.o
obj-$(CONFIG_OPENPHONE_HELLO_PLIC)        += hello-plic.o
