# Import this directory into an external Linux tree and source Kconfig from
# drivers/misc/Kconfig or another board-owned driver menu.
obj-$(CONFIG_OPENPHONE_HELLO_NPU) += hello-npu.o
obj-$(CONFIG_OPENPHONE_HELLO_DMA) += hello-dma.o
